repositories:
  remote:
   - https://repo.maven.apache.org/maven2
   - https://stocksoftware.jfrog.io/stocksoftware/maven2

artifacts:
  idea_codestyle: au.com.stocksoftware.idea.codestyle:idea-codestyle:xml:1.14

  javax_annotation: org.realityforge.javax.annotation:javax.annotation:jar:1.0.1

  javax_json: org.glassfish:javax.json:jar:1.1

  autocommon: com.google.auto:auto-common:jar:0.10
  javapoet: com.squareup:javapoet:jar:1.12.0
  guava: com.google.guava:guava:jar:27.1-jre

  #test deps
  compile_testing: com.google.testing.compile:compile-testing:jar:0.18-rf
  truth: com.google.truth:truth:jar:0.44
  junit: junit:junit:jar:4.12
  hamcrest_core: org.hamcrest:hamcrest-core:jar:1.3

  testng: org.testng:testng:jar:6.8
