repositories:
  remote:
   - https://stocksoftware.jfrog.io/stocksoftware/maven2
   - https://repo.maven.apache.org/maven2

artifacts:
  idea_codestyle: au.com.stocksoftware.idea.codestyle:idea-codestyle:xml:1.17

  javax_annotation: org.realityforge.javax.annotation:javax.annotation:jar:1.1.1

  javax_json: org.glassfish:javax.json:jar:1.1

  javapoet: com.squareup:javapoet:jar:1.13.0
  guava: com.google.guava:guava:jar:27.1-jre

  testng: org.testng:testng:jar:6.8
